// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYr9HMfdITDKOFot_JCEu51CL0KYVOK48',
    appId: '1:195231222527:android:cc3b99728d06fdfd84daca',
    messagingSenderId: '195231222527',
    projectId: 'social-media-app-5e013',
    storageBucket: 'social-media-app-5e013.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSiSSrkY8UyrG-sQwdDthhE-XSUicuu6g',
    appId: '1:195231222527:ios:96efa70c29d7f2a884daca',
    messagingSenderId: '195231222527',
    projectId: 'social-media-app-5e013',
    storageBucket: 'social-media-app-5e013.appspot.com',
    androidClientId: '195231222527-a3i62a4vqij0ovvvfjumga37bifa62nf.apps.googleusercontent.com',
    iosClientId: '195231222527-eimfnea2qfjrsep8h35dnelf268ivv48.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaAppSw25',
  );
}
